# This file was automatically generated on Thu 13 Aug 2026 12:19:06 BST from
# source: /dls_sw/prod/R3.14.12.7/support/IDLAB-BUILDER/1-77/etc/makeIocs/TS02K-CS-IOC-01.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
TOP = .
include $(TOP)/configure/CONFIG

DIRS += configure
DIRS += TS02K-CS-IOC-01App/Db
DIRS += TS02K-CS-IOC-01App/src
DIRS += iocBoot/iocTS02K-CS-IOC-01
DIRS += TS02K-CS-IOC-01App/opi/edl

include $(TOP)/configure/RULES_TOP

