/* This file was automatically generated on Thu 13 Aug 2026 12:19:05 BST from
 * source: /dls_sw/prod/R3.14.12.7/support/IDLAB-BUILDER/1-77/etc/makeIocs/TS02K-CS-IOC-01.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

